
- name: Deploy machines
  maas_machine:
    maas_url: "{{ maas_url }}"
    api_key: "{{ api_key }}"
    state: present
    meta_data:
      group_name: "{{ deploy_item.group }}"
      target_os: "{{ deploy_item.os | default('centos') }}"
    tags_match: "{{ deploy_item.match.tags }}"
    target_os: "{{ deploy_item.os | default('centos') }}"
    batch_deploy: "{{ deploy_item.size }}"
  async: 1200
  poll: 0
  with_items: "{{ deploy_machines }}"
  loop_control:
    loop_var: deploy_item
  register: async_results

- name: Wait for deploying
  async_status:
    jid: "{{ async_result_item.ansible_job_id }}"
  with_items: "{{ async_results.results }}"
  loop_control:
    loop_var: async_result_item
  register: async_poll_results
  until: async_poll_results.finished
  retries: 300    

- set_fact:
    deploy_results: "{{ async_poll_results }}"