
- hosts: localhost
  tags:
  - inventory
  connection: local
  gather_facts: no
  tasks:
  - name: Add all hosts in all clusters to an ansible host group named 'clusters'
    include_tasks: add_cluster_hosts.yaml
    with_items: "{{ cluster_list }}"
    loop_control:
      loop_var: cluster_item
  
- hosts: ganglia-nagios-server
  become: yes
  pre_tasks:
  - name: Prepare packages
    include_tasks: packages_prepare.yaml
    when: act == 'install'
  roles:
  - { role: gmetad, tags: ['gmetad'] }     
  - { role: gmond_localhost, tags: ['gmond'] }
  - { role: ganglia_web, tags: ['ganglia_web'] }
  
- hosts: clusters
  become: yes
  pre_tasks:
  - name: Prepare packages
    include_tasks: packages_prepare.yaml
    when: act == 'install'
  roles:
  - { role: gmond, tags: ['gmond'] }
