- hosts: localhost
  tags:
  - inventory
  connection: local
  gather_facts: no
  tasks:
  - name: Overwrite the cluster_list when 'single_cluster' is defined
    set_fact:
      cluster_list:
      - "{{ single_cluster }}"
    when: single_cluster is defined
  - name: Create host group for hosts in the cluster when 'single_cluster' is defined
    include_tasks: add_single_cluster_hosts.yaml
    when: single_cluster is defined
  - name: Add all hosts in all clusters to an ansible host group named 'clusters'
    include_tasks: add_cluster_hosts.yaml
    with_items: "{{ cluster_list }}"
    loop_control:
      loop_var: cluster_item
  # - name: Dump hosts in 'clusters' group
    # debug:
      # msg: "host: {{ item }}, ansible_host: {{ hostvars[item]['ansible_host'] }}, cluster_role: {{ hostvars[item]['cluster_role'] }}, head: {{ hostvars[item]['gmond_cluster_head'] }}"
    # with_items: "{{ groups['clusters'] }}"
  
- hosts: ganglia-nagios-server
  become: yes
  pre_tasks:
  - name: Prepare packages
    include_tasks: packages_prepare.yaml
    tags:
    - gmetad
    - gmond
    - ganglia_web
    - nagios_core
    when: act == 'install'
  roles:
  - { role: gmetad, tags: ['gmetad'] }     
  - { role: gmond_localhost, tags: ['gmond'] }
  - { role: ganglia_web, tags: ['ganglia_web'] }
  - { role: nagios_core, tags: ['nagios_core'] }
  
- hosts: clusters
  gather_facts: yes
  become: yes
  pre_tasks:
  - name: Prepare packages
    include_tasks: packages_prepare.yaml
    tags:
    - gmond
    when: act == 'install' or act == 'cluster_install'
  roles:
  - { role: gmond, tags: ['gmond'] }
  
- hosts: clusters
  gather_facts: yes
  become: yes
  roles:
  - { role: ganglia-nagios-client, tags: ['ganglia_nagios'] }
  
- hosts: ganglia-nagios-server
  become: yes
  roles:
  - { role: ganglia-nagios-server, tags: ['ganglia_nagios'] }
