- block:
  
  - name: Check whether the contact has already been in the admin group
    become: yes
    shell: grep ',{{ item }}' /etc/nagios/objects/contacts.cfg
    register: result
    ignore_errors: yes
  
  - name: Delete contact from the admin group
    become: yes
    shell: sed -i 's/,{{ item }}//g' /etc/nagios/objects/contacts.cfg
    when: result is succeeded

  when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'

