# tasks to initialize config of ganglia-web on the monitored hosts

- block:

  - name: Generate username and password
    shell: htpasswd -bc {{ ganglia_web_auth_file }} {{ ganglia_web_username }} {{ ganglia_web_password }}
  
  - name: Copy httpd config file
    template:
      src: ganglia.conf.j2
      dest: /etc/httpd/conf.d/ganglia.conf
      
  - name: Enable and start httpd with systemd
    systemd:
      name: httpd
      state: started
      enabled: yes
      
  # Something goes wrong with the ganglia when using template or copy here
  # - name: Copy php config file
    # template:
      # src: conf.php.j2
      # dest: /etc/ganglia/conf.php
      
  - name: Modify php config file
    lineinfile:
      path: /etc/ganglia/conf.php
      state: present
      line: "$conf['auth_system'] = '{{ ganglia_web_auth_system }}'"
      insertbefore: '\?>'

  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

