# tasks to update nagios core configuration on monitoring hosts

- block:
    
  - name: Configure for system requirement
    include_tasks: config_system.yaml     
  
  - name: Create blank contacts file
    template:
      src: contacts_blank.cfg.j2
      dest: /etc/nagios/objects/contacts.cfg
      
  - name: Add default admin user to contacts file
    blockinfile:
      path: /etc/nagios/objects/contacts.cfg
      block: |
        define contact {
          contact_name                   {{ nagios_admin_username }}
          use                            generic-contact		
          alias                          Nagios Default Admin		
          service_notification_options   w,u,c,r,f,s
          host_notification_options      d,u,r,f,s
          email                          {{ nagios_admin_email }}
        }
      marker: "# {mark} add default admin"
      
  - name: Add default admin group to contacts file
    blockinfile:
      path: /etc/nagios/objects/contacts.cfg
      block: |
        define contactgroup {
          contactgroup_name       admins
          alias                   Nagios Default Admin Group
          members                 {{ nagios_admin_username }},{{ nagios_admin_contacts | join(',') }}
        }
      marker: "# {mark} create default admin group"
  
  - name: Add each contact to contacts file
    blockinfile:
      path: /etc/nagios/objects/contacts.cfg
      block: |
        define contact{
          contact_name                   {{ item.contact_name }}	
          use                            generic-contact		
          alias                          {{ item.alias | default(item.contact_name) }}		
          service_notification_options   {{ item.service_notification_options | default('u,c,r') }}
          host_notification_options      {{ item.host_notification_options | default('d,u,r') }}
          email                          {{ item.email }}
        }
      marker: "# {mark} add contact {{ item.contact_name }}"
    with_items: "{{ nagios_contacts }}"
  
  - name: Generate username and password for nagios web
    shell: htpasswd -bc {{ nagios_web_auth_file }} {{ nagios_admin_username }} {{ nagios_web_admin_password }}
  
  - name: Copy httpd config file
    template:
      src: nagios.conf.j2
      dest: /etc/httpd/conf.d/nagios.conf
      
  - name: Copy cgi config file
    template:
      src: cgi.cfg.j2
      dest: /etc/nagios/cgi.cfg
      
  - name: Restart nagios core with systemd
    systemd:
      name: nagios
      state: restarted
      enabled: yes
      
  - name: Restart httpd with systemd
    systemd:
      name: httpd
      state: restarted
      enabled: yes

  when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'

