# tasks to define host group and related service group checked via ganglia

- block:

  - name: Generate config files for each host group and related services definitions
    template:
      src: check_ganglia_hostgroup_servicegroup.cfg.j2
      dest: /etc/nagios/conf.d/{{ cluster_item }}_hostgroup_servicegroup.cfg
    with_items: "{{ cluster_list }}"
    loop_control:
      loop_var: cluster_item

  when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'

