
- hosts: localhost
  gather_facts: no
  connection: local
  tasks:
  - include_tasks: add_istio_installer.yaml
    when: "'istioinstaller' not in groups or groups['istioinstaller'] | length == 0"

- hosts: istioinstaller
  become: yes
  vars_files:
  - clean_vars.yaml
  tasks:
  - name: Remove accessories
    shell: kubectl {{ item }}
    args:
      chdir: "{{ istio_dir }}"
    with_items: "{{ kubectl_args }}"
    ignore_errors: yes
    when: (istio_version == "0.5.0") or
          (istio_version == "0.5.1") or
          (istio_version == "0.6.0") or
          (istio_version == "0.7.0") or
          (istio_version == "0.7.1")
          
  - name: Uninstall istio
    shell: kubectl delete -f install/kubernetes/{{ istio_choice }}.yaml
    args:
      chdir: "{{ istio_dir }}"
    ignore_errors: yes
    
  - name: Unlabel default namespace
    shell: kubectl label namespace default istio-injection-
  
  - name: Remove istio-system namespace
    shell: kubectl delete ns istio-system
    ignore_errors: yes
  
  - name: Clean istio packages
    shell: rm -rf {{ root_dir }}/istio*

  environment:
    KUBECONFIG: "{{ kubeconfig_path }}"
    PATH: "{{ ansible_env.PATH }}:{{ kubectl_path }}"

- hosts: master
  become: yes
  vars_files:
  - clean_vars.yaml
  tasks:
  - name: Clean 'MutatingAdmissionWebhook' addmission control flags
    shell: sed -i 's/MutatingAdmissionWebhook,//' {{ api_server_manifest }}
    when: remove_mut_flag
    
  - name: Clean 'ValidatingAdmissionWebhook' addmission control flags
    shell: sed -i 's/ValidatingAdmissionWebhook,//' {{ api_server_manifest }}
    when: remove_val_flag
    notify:
    - Wait api server restarts
    
  handlers:
  - name: Wait api server restarts
    shell: docker ps | grep apiserver | grep -v pause
    register: result
    until: result.stdout != ""
    retries: 10
    delay: 2
  
