
- hosts: localhost
  gather_facts: no
  connection: local
  tasks:
  - name: Add first master to istioinstaller group
    add_host:
      name: "{{ groups['master'][0] }}"
      groups: istioinstaller

- hosts: istioinstaller
  become: yes
  vars_files:
  - clean_vars.yaml
  tasks:
  - name: Uninstall istio
    shell: kubectl {{ item }}
    args:
      chdir: "{{ istio_dir }}"
    with_items: "{{ kubectl_args }}"
    ignore_errors: yes
  
  - name: Clean istio packages
    shell: rm -rf {{ root_dir }}/istio*

  environment:
    KUBECONFIG: "{{ kubeconfig_path }}"
    PATH: "{{ ansible_env.PATH }}:{{ kubectl_path }}"

- hosts: master
  become: yes
  vars_files:
  - clean_vars.yaml
  tasks:
  - name: Clean 'MutatingAdmissionWebhook' addmission control flags
    shell: sed -i 's/MutatingAdmissionWebhook,//' /etc/kubernetes/manifests/{{ api_server_manifest }}
    when: remove_mut_flag
    
  - name: Clean 'ValidatingAdmissionWebhook' addmission control flags
    shell: sed -i 's/ValidatingAdmissionWebhook//' /etc/kubernetes/manifests/{{ api_server_manifest }}
    when: remove_val_flag
    notify:
    - Wait api server restarts
    
  handlers:
  - name: Wait api server restarts
    shell: docker ps | grep apiserver | grep -v pause
    register: result
    until: result.stdout != ""
    retries: 10
    delay: 2
  
