
- hosts: localhost
  gather_facts: no
  connection: local
  tasks:
  - name: Add first master to istioinstaller group
    add_host:
      name: "{{ groups['master'][0] }}"
      groups: istioinstaller

- hosts: istioinstaller
  become: yes
  vars_files:
  - clean_vars.yml
  tasks:
  - name: Uninstall istio
    shell: kubectl {{ item }}
    args:
      chdir: "{{ istio_dir }}"
    with_items: "{{ kubectl_args }}"
    ignore_errors: yes
  
  - name: Clean istio packages
    shell: rm -rf {{ root_dir }}/istio*

  - name: Remove kubectl from current path
    shell: rm -rf /usr/bin/kubectl

  environment:
    KUBECONFIG: "{{ kubeconfig_path }}"

- hosts: master
  become: yes
  tasks:
  - name: Clean the istio needed addmission control flags
    shell: sed -i 's/NodeRestriction,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,ResourceQuota/NodeRestriction,ResourceQuota/' /etc/kubernetes/manifests/kube-apiserver.yaml

  - name: Restart kubelet service
    systemd:
      name: kubelet
      state: restarted 
  
