---
remove_mut_flag: yes
remove_val_flag: yes

kubectl_args:
- "delete secret sidecar-injector-certs -n istio-system"
- "delete csr istio-sidecar-injector.istio-system"
- "delete -f install/kubernetes/istio-sidecar-injector-with-ca-bundle.yaml"
  
