# tasks to get the kubectl and the kubeconfig files from remote hosts or urls

- block:
  
  - name: Fetch kubectl file from a remote host
    shell: "scp {{ remote_file_host_user }}@{{ remote_file_host }}:{{ remote_kubectl_path }}/kubectl {{ kubectl_path }}"
      
  - name: Fetch kubeconfig file from a remote host
    shell: "scp {{ remote_file_host_user }}@{{ remote_file_host }}:{{ remote_kubeconfig_path }} {{ kubeconfig_path }}"

  when: file_get == 'fetch'

- block:
  
  - name: Download kubectl file from url
    get_url:
      url: "{{ url_kubectl }}"
      dest: "{{ kubectl_path }}/kubectl"
  
  - name: Download kubeconfig file from url
    get_url:
      url: "{{ url_kubeconfig }}"
      dest: "{{ kubeconfig_path }}"

  when: file_get == 'url'

- name: Make kubectl executable 
  file:
    path: "{{ kubectl_path }}/kubectl"
    mode: 0744