# tasks to config the system to meet requirements by configuration of ganglia web

- block:

  - name: Disable selinux
    selinux:
      state: disabled
      
  - name: Config tcp_tw_reuse
    sysctl:
      name: net.ipv4.tcp_tw_reuse
      value: 1
      state: present
      reload: yes
      
  - name: Config tcp_tw_recycle
    sysctl:
      name: net.ipv4.tcp_tw_recycle
      value: 1
      state: present
      reload: yes
      
  - name: Check tcp_fin_timeout
    shell: sysctl -n net.ipv4.tcp_fin_timeout
    register: check_fin_result
    
  - name: Config tcp_fin_timeout
    sysctl:
      name: net.ipv4.tcp_fin_timeout
      value: "{{ ganglia_web_tcp_fin_timeout }}"
      state: present
      reload: yes
    when: check_fin_result.stdout | int > ganglia_web_tcp_fin_timeout
    
  - name: Check tcp_max_syn_backlog
    shell: sysctl -n net.ipv4.tcp_max_syn_backlog
    register: check_syn_result
    
  - name: Config tcp_max_syn_backlog
    sysctl:
      name: net.ipv4.tcp_max_syn_backlog
      value: "{{ ganglia_web_tcp_max_syn_backlog }}"
      state: present
      reload: yes
    when: check_syn_result.stdout | int < ganglia_web_tcp_max_syn_backlog
    
  - name: Check tcp_max_tw_buckets
    shell: sysctl -n net.ipv4.tcp_max_tw_buckets
    register: check_tw_result
    
  - name: Config tcp_max_tw_buckets
    sysctl:
      name: net.ipv4.tcp_max_tw_buckets
      value: "{{ ganglia_web_tcp_max_tw_buckets }}"
      state: present
      reload: yes
    when: check_tw_result.stdout | int < ganglia_web_tcp_max_tw_buckets

  when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'

