# tasks to setup ganglia-web on the monitoring hosts

- block:

  - name: Upgrade yum packages
    yum:
      name: '*'
      state: latest
      
  - name: Install epel release
    yum:
      name: epel-release
      state: latest      
      
  - name: Install ganglia-web (yum)
    yum:
      name: ganglia-web
      state: latest
    
  - name: Configure for system requirement
    include_tasks: config_system.yaml  
  
  - name: Configure ganglia-web
    include_tasks: init_config_ganglia_web.yaml

  - name: Enable and start httpd with systemd
    systemd:
      name: httpd
      state: started
      enabled: yes

  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

