# tasks to setup ganglia-web on the monitoring hosts

- block:

  - name: Install rrdtool (yum)
    yum:
      name: rrdtool
      state: latest      

  - name: Install ganglia (yum)
    yum:
      name: ganglia
      state: latest
      
  - name: Install ganglia-web (yum)
    yum:
      name: ganglia-web
      state: latest
    
  - name: Configure for system requirement
    include_tasks: config_system.yaml  
  
  - name: Configure ganglia-web
    include_tasks: init_config_ganglia_web.yaml

  when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'

