# tasks to update ganglia web configuration on monitoring hosts

- block:
    
  - name: Configure for system requirement
    include_tasks: config_system.yaml  
  
  - name: Generate username and password
    shell: htpasswd -bc {{ ganglia_web_auth_file }} {{ ganglia_web_username }} {{ ganglia_web_password }}
  
  - name: Copy httpd config file
    template:
      src: ganglia.conf.j2
      dest: /etc/httpd/conf.d/ganglia.conf
      
  - name: Modify php config file
    lineinfile:
      path: /etc/ganglia/conf.php
      state: present
      regexp: 'auth_system'
      line: "$conf['auth_system'] = '{{ ganglia_web_auth_system }}'"
      insertbefore: '\?>'
  
  - name: Restart httpd with systemd
    systemd:
      name: httpd
      state: restarted
      enabled: yes

  when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'

