# delete each contact from the cluster contact group

- block:
  
  - name: Delete contact from the contact group
    include_tasks: del_cluster_contacts_relay.yaml
    with_items: "{{ cluster_list }}"
    loop_control:
      loop_var: cluster_item
    
  - name: Restart nagios with systemd
    systemd:
      name: nagios
      state: restarted

  when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'

