# delete each contact from the cluster contact group

- block:
  
  - name: Delete contact from the contact group
    include_tasks: del_cluster_contacts.yaml
    with_items: "{{ hostvars[groups[cluster_item][0]]['cluster_contacts'] | default([]) }}"

  when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'

