
init_client: no
python35_manual: no

maas_url: "http://maas.adp.gic.ericsson.se/MAAS/"
api_key: "EP2QFqr9RhYBHEpvgd:WfwgyKek6xhYHXRQBn:K6ftkVYLnMLaesm2phgtqnEjtDULKjkW"

deploy_machines:
- group: centosserver
  size: 2
  match:
    tags:
    - REMOTE-MGMT
- group: ubuntuserver
  size: 2
  match:
    tags:
    - auto-test
  os: ubuntu
- group: monitorserver
  size: 1
  match:
    tags:
    - REMOTE-MGMT
