# handlers
- name: Enable and start httpd with systemd
  systemd:
    name: httpd
    state: started
    enabled: yes

- name: Restart httpd with systemd
  systemd:
    name: httpd
    state: restarted
    enabled: yes
