# tasks to define a host object representing the current host and add to the related cfg file
 
- name: Get hostname by shell
  shell: hostname
  register: result
  when: ansible_not_get_facts | default('no') | bool

- name: Create facts when not gathered
  set_fact:
    ansible_fqdn: "{{ result.stdout }}{{ known_domain }}"
  when: ansible_not_get_facts | default('no') | bool

- name: Define host and add to cfg file
  delegate_to: "{{ outer_item }}"
  vars:
    outer_ansible_distribution: "{{ hostvars[outer_item]['ansible_distribution'] }}"
  include_tasks: "create_host_definition.yaml"       
  with_items: "{{ cluster_list }}"
  loop_control:
    loop_var: cluster_item
  when: cluster_item in group_names

