# tasks to remove data source of each cluster from config file

- block:
    
  - set_fact:
      member_host: "{{ groups[item][0] }}"
      
  - name: Remove cluster data source
    lineinfile:
      path: /etc/ganglia/gmetad.conf
      insertafter: "^data_source"
      line: "data_source \"{{ hostvars[member_host]['gmond_cluster_name'] }}\" {{ gmetad_clusters_poll_interval }} {{ hostvars[member_host]['gmond_cluster_head'] | join(' ') }}"
      state: present

  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

