# tasks to config the system to meet requirements by configuration of gmetad

- block:

  - name: Disable selinux
    selinux:
      state: disabled

  when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'

