# tasks to remove data source of each cluster from config file

- block:      
  - name: Remove cluster data source
    lineinfile:
      path: /etc/ganglia/gmetad.conf
      regexp: "^data_source \"{{ item }}\" "
      state: absent

  when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'

