# tasks to setup gmetad on the monitoring hosts

- block:    

  - name: Install rrdtool (yum)
    yum:
      name: rrdtool
      state: latest
  
  - name: Install ganglia (yum)
    yum:
      name: ganglia
      state: latest
      
  - name: Install gmetad (yum)
    yum:
      name: ganglia-gmetad
      state: latest
    
  - name: Configure for system requirement
    include_tasks: config_system.yaml  
  
  - name: Configure gmetad
    include_tasks: init_config_gmetad.yaml
    
  - name: Enable and start gmetad with systemd
    systemd:
      name: gmetad
      state: started
      enabled: yes

  when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'

