# tasks to uninstall gmetad on the monitoring hosts

- block:      
      
  - name: Stop gmetad service with systemd
    systemd:
      name: gmetad
      state: stopped
      enabled: no
    ignore_errors: yes

  - name: Uninstall rrdtool package
    yum:
      name: rrdtool
      state: absent
    
  - name: Uninstall all gmetad related packages
    yum:
      name: 'ganglia*'
      state: absent

  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

