# tasks to install istio auto sidecar injector

- name: Download missing scripts when istio version = 0.5.0 or 0.5.1
  get_url:
    url: "{{ item }}"
    dest: "{{ istio_kube_dir }}"
    mode: 0766
  with_items: "{{ missing_script_paths }}"
  when: istio_version == "0.5.0" or istio_version == "0.5.1"

- name: Generate k8s CA signed cert/key
  shell: ./webhook-create-signed-cert.sh --service istio-sidecar-injector --namespace istio-system --secret sidecar-injector-certs
  args:
    chdir: "{{ istio_kube_dir }}"
    
- name: Install sidecar injection configmap
  shell: kubectl apply -f istio-sidecar-injector-configmap-release.yaml
  args:
    chdir: "{{ istio_kube_dir }}"

- name: Set the caBundle in the webhook
  shell: cat istio-sidecar-injector.yaml | ./webhook-patch-ca-bundle.sh > istio-sidecar-injector-with-ca-bundle.yaml
  args:
    chdir: "{{ istio_kube_dir }}"

- name: Install sidecar injector webhook
  shell: kubectl apply -f istio-sidecar-injector-with-ca-bundle.yaml
  args:
    chdir: "{{ istio_kube_dir }}"
    
- name: Set the default namespace to use auto injection
  shell: kubectl label namespace default istio-injection=enabled
