# tasks to install istio core components
- name: Create istio-system namespace
  shell: kubectl create namespace istio-system
  register: result_ns
  until: result_ns is success
  retries: 10
 
- name: Install istio core components
  shell: kubectl create -f {{ istio_choice }}.yaml
  args:
    chdir: "{{ istio_kube_dir }}"
  register: result
  until: result is success
  retries: 10
