---

- name: Install istio core components
  become: yes
  include_tasks: install_istio_core.yml

- name: Install istio sidecar auto injector
  become: yes
  when: {{ istio_sidecar_inject }} == auto
  include_tasks: install_sidecar_injector.yml