---
ansible_not_get_facts: no
# ansible_distribution: CentOS

# a variable to list all clusters to be monitored, the name of cluster must be identical to the corresponding ansible host group name
cluster_list:
#- goes
- earth
#- calipso
#- ladee
#- adpci06
#- adpci07
#- timed

# a variable indicate the type of the cluster which could be overwrited in the group's vars
cluster_type: kubespray

# customized python modules for gmond on the monitored hosts
# names listed must be identical to the names of files in roles/gmond/templates/conf.d and roles/gmond/files/python_modules
gmond_python_modules:
- systemd_stats
- mem_stats
- netstats
- docker_ps
- node_ready

# list of names of other files required by the customized modules
gmond_python_modules_attachs:
- MetricBook.py

# list of commands needed to be applied required by the customized modules
gmond_python_modules_exec:
- usermod -a -G root ganglia
- usermod -a -G root ganglia
- usermod -a -G docker ganglia
- yum install -y python2-pip
- yum install -y python-yaml
- pip install requests_unixsocket

# gmond python modules that only deployed on the host running as the head of the cluster
gmond_head_python_modules: []

# list of names of other files required by the customized modules for the head
gmond_head_python_modules_attachs: []

# list of commands needed to be applied required by the customized modules for the head
gmond_head_python_modules_exec: []

# list services managed by systemd on the monitored hosts which are checked, could be overwrited in the group's vars
gmond_systemd_check_services:
- kubelet
- docker
- etcd

# multicast or unicast
gmond_mode: multicast

# identical across clusters
gmond_multicast_address: 239.2.11.71

# the value of 'mute' in /etc/ganglia/gmond.conf on the monitored hosts running gmond
gmond_mute: 'no'

# the value of 'deaf' in /etc/ganglia/gmond.conf on the monitored hosts running gmond  
gmond_deaf: 'no'

# the value of 'max_udp_msg_len' in /etc/ganglia/gmond.conf on the monitored hosts running gmond
gmond_max_udp_msg_len: 1472

# the value of 'host_dmax' in /etc/ganglia/gmond.conf on the monitored hosts running gmond 
gmond_host_dmax: 86400

# the value of 'host_tmax' in /etc/ganglia/gmond.conf on the monitored hosts running gmond 
gmond_host_tmax: 20

# the value of 'cleanup_threshold' in /etc/ganglia/gmond.conf on the monitored hosts running gmond   
gmond_cleanup_threshold: 300

# the value of 'send_metadata_interval' in /etc/ganglia/gmond.conf on the monitored hosts running gmond
gmond_send_metadata_interval: 30

# the port gmond listening on with udp
gmond_udp_recv_port: 8649

# the port gmond sending data to with udp, should be equal to the listening port above
gmond_udp_send_port: 8649

# the buffer size for gmond's receiving udp channel
gmond_udp_recv_buffer: 10485760

# the interval that the gmond sending data
gmond_udp_send_ttl: 1




# whether enable the nagios checking ganglia services' dependencies to supress massive alerts
# when it is enalbed, all the nagios checking ganglia services on each host will depend on the gmond heartbeat service
nagios_check_ganglia_service_dependency: yes

# interval checking ganglia metric by nagios, unit is 1 min, can be less than 1, can be specified for each individual checking service
nagios_check_ganglia_check_interval: 2

# retry interval checking ganglia metric by nagios, unit is 1 min, can be less than 1, can be specified for each individual checking service
nagios_check_ganglia_check_retry_interval: 1

# maximal check attempts for ganglia metric check retry by nagios, can be specified for each individual checking service
nagios_check_ganglia_check_max_retries: 2

# interval sending notification by nagios, unit is 60s, can be less than 1, can be specified for each individual checking service
nagios_check_ganglia_notification_interval: 60

# maximal time losing heartbeat before off a host in sec
nagios_check_ganglia_heartbeat_threshold: 60

# whether notify the checking hearbeat service to the cluster contact
nagios_check_ganglia_heartbeat_cluster_notify: yes

# whether notify the checking hearbeat service
nagios_check_ganglia_heartbeat_notify: yes

# path to the plugins used by nagios to check on ganglia
nagios_check_ganglia_plugins_path: /usr/share/ganglia/nagios

# host check interval by nagios in min, can be less than 1
nagios_host_check_interval: 3

# host check retry interval by nagios in min, can be less than 1
nagios_host_check_retry_interval: 1

# maximal check attempts for host check retry by nagios
nagios_host_check_max_retries: 3

# host notification resend interval in min
nagios_host_notification_interval: 60


# ganglia metrics checked by nagios with warning and critical values
nagios_check_ganglia_metrics:
- name: load_one
  oper: more
  warn_val: 5
  crit_val: 7
# whether send notification
  notify: yes
# whether send notification to cluster-specific user
  cluster_notify: no
# checking interval in min, can be less than 1
  check_interval: 2
# retry checking interval in min, can be less than 1
  retry_interval: 2
# number of time to retry checking
  max_retries: 2
# notification interval in min
  retry_interval: 60
- name: cpu_idle
  oper: less
  warn_val: 50
  crit_val: 10
- name: cpu_wio
  oper: more
  warn_val: 50
  crit_val: 90
- name: disk_free_percent_rootfs
  oper: less
  warn_val: 40
  crit_val: 10
- name: mem_used_percent
  oper: more
  warn_val: 80
  crit_val: 90
- name: service-status-kubelet
  oper: less
  warn_val: 1
  crit_val: 1.5
  cluster_role:
  - worker
  - master
  cluster_type:
  - kubespray
  - erikube
- name: service-status-docker
  oper: less
  warn_val: 1
  crit_val: 1.5
  cluster_role:
  - worker
  - master
- name: docker_ps
  oper: less
  warn_val: 1
  crit_val: 1.5
  cluster_role:
  - worker
  - master
- name: service-status-etcd
  oper: less
  warn_val: 1
  crit_val: 1.5
  cluster_role:
  - master
  cluster_type:
  - kubespray
- name: service-status-etcd_container
  oper: less
  warn_val: 1
  crit_val: 1.5
  cluster_role:
  - master
  cluster_type:
  - erikube
- name: node_ready
  oper: less
  warn_val: 1
  crit_val: 1.5
  cluster_role:
  - master
  - worker
  cluster_type:
  - kubespray
  - erikube

# services checked targeting only on the host running as the head of the cluster
nagios_check_ganglia_head_metrics: []


# Path to kubeconfig file for kubectl
kubeconfig_path: /etc/kubernetes/admin.conf

# Path to kubectl
kubectl_path: /usr/local/bin

# CA cert path for the kubernetes cluster
kube_ca_cert: /etc/kubernetes/ssl/ca.pem

# CA key path for the kubernetes cluster
kube_ca_key: /etc/kubernetes/ssl/ca-key.pem

# Temporary dir storing the genterated kube cert and key for ganglia client on the local host
local_cert_key_dir: /root/kube_cert_key