---
# the buffer size for gmond's receiving udp channel
gmond_udp_recv_buffer: 10485760

# the interval polling metrics from gmond on localhost
# note that the storage archi of rrd (rra) is assuming 15 seconds polling by default, change this should change the rra also
gmetad_localhost_poll_interval: 15

# the interval polling metrics from gmonds on hosts in clusters
gmetad_clusters_poll_interval: 15

# the grid name
gmetad_grid_name: rnd_tenant

# username to login ganglia web
ganglia_web_username: adminganglia

# password to login ganglia web
ganglia_web_password: admin

# auth file for ganglia web used by Apache, full path is required
ganglia_web_auth_file: /etc/ganglia/http.auth

# switch of ganglia web auth system configured in /etc/ganglia/conf.php
ganglia_web_auth_system: disabled





# name of admin user for nagios
nagios_admin_username: adminnagios

# email address for admin user
nagios_admin_email: xxxx@example.com

# password for admin user to login to nagios web
nagios_web_admin_password: admin

# auth file for nagios web used by Apache, full path is required
nagios_web_auth_file: /etc/nagios/http.auth

# contacts information used in nagios
# some elements can be optional with default values:
# alias: identical to contact_name by default
# service_notification_options: 'u,c,r' by default
# host_notification_options: 'd,u,r' by default
nagios_contacts:
- contact_name: xxx
  alias: xxx
  email: xxx
  service_notification_options: w,u,c,r,f,s
  host_notification_options: d,u,r,f,s

# names of the contacts in the admin group
nagios_admin_contacts:
- xxx

# path to the plugins used by nagios to check on ganglia
nagios_check_ganglia_plugins_path: /usr/share/ganglia/nagios/
    