# tasks to add attachments for customized gmond python modules

- name: Add atachments
  copy:
    src: "{{ item }}"
    dest: /usr/lib64/ganglia/python_modules/
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'
  
- name: Add atachments
  copy:
    src: "{{ item }}"
    dest: /usr/lib/ganglia/python_modules/
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

