# tasks to add customized python modules and related files on monitored hosts
  
- name: Add customized gmond python modules
  include_tasks: add_python_modules.yaml
  with_items: "{{ gmond_python_modules | default([]) }}"

- name: Add attachments for customized gmond python modules
  include_tasks: add_python_modules_attach.yaml
  with_items: "{{ gmond_python_modules_attachs | default([]) }}"

- name: Apply executions for customized gmond python modules
  include_tasks: apply_python_modules_exec.yaml
  with_items: "{{ gmond_python_modules_exec | default([]) }}"
  
- block:
  - name: Add customized gmond python modules for cluster head
    include_tasks: add_python_modules.yaml
    with_items: "{{ gmond_head_python_modules | default([]) }}"
  
  - name: Add attachments for customized gmond python modules for cluster head
    include_tasks: add_python_modules_attach.yaml
    with_items: "{{ gmond_head_python_modules_attachs | default([]) }}"
    
  - name: Apply executions for customized gmond python modules for cluster head
    include_tasks: apply_python_modules_exec.yaml
    with_items: "{{ gmond_head_python_modules_exec | default([]) }}"
  
  when: (gmond_cluster_head[0].split(':')[0] == ansible_ens192.ipv4.address) or
        (gmond_cluster_head[0].split(':')[0] == ansible_host) or
        (gmond_cluster_head[0].split(':')[0] == inventory_hostname) or
        (gmond_cluster_head[0].split(':')[0] == ansible_hostname)
