# tasks to update gmond configuration on monitored hosts
  
- name: Add customized gmond python modules and related files
  include_tasks: add_modules_and_files.yaml

- name: Restart gmond service
  include_tasks: restart_gmond_service.yaml

