# tasks to update gmond configuration on monitored hosts

- block:     
  
  - name: Copy config file with multicast mode
    template:
      src: gmond_multicast.conf.j2
      dest: /etc/ganglia/gmond.conf
    when: gmond_mode == 'multicast'
    
  - name: Add customized gmond python modules
    include_tasks: add_python_modules.yaml
    with_items: "{{ gmond_python_modules }}"

  - name: Restart gmond with systemd
    systemd:
      name: gmond
      state: restarted
      enabled: yes

  when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'

