# tasks to update gmond configuration on monitored hosts

- name: Get gmond cluster name which is identical to the cluster's name
  set_fact:
    gmond_cluster_name: "{{ item }}"
  with_items: "{{ cluster_list }}"
  when: item in group_names
  
- name: Add customized gmond python modules
  include_tasks: add_python_modules.yaml
  with_items: "{{ gmond_python_modules }}"

- name: Add attachments for customized gmond python modules
  include_tasks: add_python_modules_attach.yaml
  with_items: "{{ gmond_python_modules_attachs }}"
  
- block:
  - name: Add customized gmond python modules for cluster head
    include_tasks: add_python_modules.yaml
    with_items: "{{ gmond_head_python_modules | default([]) }}"
  
  - name: Add attachments for customized gmond python modules for cluster head
    include_tasks: add_python_modules_attach.yaml
    with_items: "{{ gmond_head_python_modules_attachs | default([]) }}"
  
  when: (gmond_cluster_head[0].split(':')[0] == ansible_ens192.ipv4.address) or
        (gmond_cluster_head[0].split(':')[0] == ansible_host) or
        (gmond_cluster_head[0].split(':')[0] == inventory_hostname) or
        (gmond_cluster_head[0].split(':')[0] == ansible_hostname)

- block:
  
  - name: Copy config file with multicast mode
    template:
      src: gmond_multicast.conf.j2
      dest: /etc/ganglia/gmond.conf
    when: gmond_mode == 'multicast'
    
  - name: Restart gmond with systemd
    systemd:
      name: gmond
      state: restarted
      enabled: yes
  
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'
  
- block:
  
  - name: Copy config file with multicast mode
    template:
      src: gmond_multicast_ubuntu.conf.j2
      dest: /etc/ganglia/gmond.conf
    when: gmond_mode == 'multicast'
    
  - name: Restart gmond with systemd
    systemd:
      name: ganglia-monitor
      state: restarted
      enabled: yes
  
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

