# tasks to restart gmond service on monitored hosts

- name: Get gmond cluster name which is identical to the cluster's name
  set_fact:
    gmond_cluster_name: "{{ item }}"
  with_items: "{{ cluster_list }}"
  when: item in group_names        

- block:
  
  - name: Copy config file with multicast mode
    template:
      src: gmond_multicast.conf.j2
      dest: /etc/ganglia/gmond.conf
    when: gmond_mode == 'multicast'
    
  - name: Restart gmond with systemd
    systemd:
      name: gmond
      state: restarted
      enabled: yes
  
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'
  
- block:
  
  - name: Copy config file with multicast mode
    template:
      src: gmond_multicast_ubuntu.conf.j2
      dest: /etc/ganglia/gmond.conf
    when: gmond_mode == 'multicast'
    
  - name: Restart gmond with systemd
    systemd:
      name: ganglia-monitor
      state: restarted
      enabled: yes
  
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

