# tasks to setup gmond on the monitored hosts

- block:     
  
  - name: Install ganglia (yum)
    yum:
      name: ganglia
      state: latest    
    
  - name: Install gmond python (yum)
    yum:
      name: ganglia-gmond-python
      state: latest
      
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'        
    
- name: Install gmond python (apt)
  apt:
    name: ganglia-monitor-python
    state: latest
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'      
    
- name: Configure for system requirement
  include_tasks: config_system.yaml  

- name: Configure gmond
  include_tasks: init_config_gmond.yaml
  
- name: Add customized gmond python modules
  include_tasks: add_python_modules.yaml
  with_items: "{{ gmond_python_modules }}"

- name: Enable and start gmond with systemd
  systemd:
    name: gmond
    state: started
    enabled: yes
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'
  
- name: Enable and start gmond with systemd
  systemd:
    name: ganglia-monitor
    state: started
    enabled: yes      
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

