# tasks to setup gmond on the monitored hosts

- block:     
  
  - name: Install ganglia (yum)
    yum:
      name: ganglia
      state: latest    
    
  - name: Install gmond python (yum)
    yum:
      name: ganglia-gmond-python
      state: latest
    
  - name: Configure for system requirement
    include_tasks: config_system.yaml  
  
  - name: Configure gmond
    include_tasks: init_config_gmond.yaml

  - name: Enable and start gmond with systemd
    systemd:
      name: gmond
      state: started
      enabled: yes

  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

