# tasks to setup gmond on the monitored hosts

- block:     
  
  - name: Install ganglia (yum)
    yum:
      name: ganglia
      state: latest    
    
  - name: Install gmond python (yum)
    yum:
      name: ganglia-gmond-python
      state: latest
      
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'        
    
- block:

  - name: Install gmond (apt)
    apt:
      name: ganglia-monitor
      state: latest
  
  - name: Install gmond python (apt)
    apt:
      name: ganglia-monitor-python
      state: latest
  
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'      

- name: Configure for system requirement
  include_tasks: config_system.yaml
  
- name: Start gmond service
  include_tasks: start_gmond_service.yaml
  
- name: Add customized gmond python modules and related files
  include_tasks: add_modules_and_files.yaml

- name: Restart gmond service
  include_tasks: restart_gmond_service.yaml
