# tasks to setup gmond on the monitored hosts

- block:     
  
  - name: Install ganglia (yum)
    yum:
      name: ganglia
      state: latest    
    
  - name: Install gmond python (yum)
    yum:
      name: ganglia-gmond-python
      state: latest
      
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'        
    
- block:

  - name: Install gmond (apt)
    apt:
      name: ganglia-monitor
      state: latest
  
  - name: Install gmond python (apt)
    apt:
      name: ganglia-monitor-python
      state: latest
  
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'      
    
- name: Configure for system requirement
  include_tasks: config_system.yaml  

- name: Configure gmond
  include_tasks: init_config_gmond.yaml
  
- name: Add customized gmond python modules
  include_tasks: add_python_modules.yaml
  with_items: "{{ gmond_python_modules }}"

- name: Add attachments for customized gmond python modules
  include_tasks: add_python_modules_attach.yaml
  with_items: "{{ gmond_python_modules_attachs }}"
  
- block:
  - name: Add customized gmond python modules for cluster head
    include_tasks: add_python_modules.yaml
    with_items: "{{ gmond_head_python_modules | default([]) }}"
  
  - name: Add attachments for customized gmond python modules for cluster head
    include_tasks: add_python_modules_attach.yaml
    with_items: "{{ gmond_head_python_modules_attachs | default([]) }}"
  
  when: (gmond_cluster_head[0].split(':')[0] == ansible_ens192.ipv4.address) or
        (gmond_cluster_head[0].split(':')[0] == ansible_host) or
        (gmond_cluster_head[0].split(':')[0] == inventory_hostname) or
        (gmond_cluster_head[0].split(':')[0] == ansible_hostname)

- name: Enable and start gmond with systemd
  systemd:
    name: gmond
    state: started
    enabled: yes
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'
  
- name: Enable and start gmond with systemd
  systemd:
    name: ganglia-monitor
    state: restarted
    enabled: yes      
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

