# tasks to uninstall gmond on the monitored hosts

- block:      
      
  - name: Stop gmond service with systemd
    systemd:
      name: gmond
      state: stopped
      enabled: no
    ignore_errors: yes
  
  - name: Uninstall all gmond related packages
    yum:
      name: 'ganglia*'
      state: absent
      
  - name: Remove all python modules
    become: yes
    shell: rm -rf /usr/lib64/ganglia/python_modules/*

  when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'
  
- block:      
      
  - name: Stop gmond service with systemd
    systemd:
      name: ganglia-monitor
      state: stopped
      enabled: no
    ignore_errors: yes
  
  - name: Uninstall gmond python package
    apt:
      name: ganglia-monitor-python
      state: absent
      purge: yes
      autoremove: yes
  
  - name: Uninstall gmond package
    apt:
      name: ganglia-monitor
      state: absent
      purge: yes
      autoremove: yes
      
  - name: Remove all python modules
    become: yes
    shell: rm -rf /usr/lib/ganglia/python_modules/*

  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  
- name: Remove all pyconf files
  become: yes
  shell: rm -rf /etc/ganglia/conf.d/*

