# tasks to uninstall gmond on the monitored hosts

- block:      
      
  - name: Stop gmond service with systemd
    systemd:
      name: gmond
      state: stopped
      enabled: no
    ignore_errors: yes
  
  - name: Uninstall all gmond related packages
    yum:
      name: 'ganglia*'
      state: absent 

  when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'

