# tasks to uninstall gmond on the monitored hosts

- block:      
      
  - name: Stop gmond service with systemd
    systemd:
      name: gmond
      state: stopped
      enabled: no
    ignore_errors: yes
  
  - name: Uninstall all gmond related packages
    yum:
      name: 'ganglia*'
      state: absent 

  when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'
  
- block:      
      
  - name: Stop gmond service with systemd
    systemd:
      name: ganglia-monitor
      state: stopped
      enabled: no
    ignore_errors: yes
  
  - name: Uninstall all gmond related packages
    apt:
      name: 'ganglia-monitor*'
      state: absent 

  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

