# tasks to update gmond configuration on the localhost

- block:
    
  - name: Configure for system requirement
    include_tasks: config_system.yaml  

  - name: Restart gmond with systemd
    systemd:
      name: gmond
      state: restarted
      enabled: yes

  when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'

