# tasks to update gmond configuration on the localhost

- block:
    
  - name: Configure for system requirement
    include_tasks: config_system.yaml  
  
  - name: Copy config file for localhost
    template:
      src: gmond_localhost.conf.j2
      dest: /etc/ganglia/gmond.conf

  - name: Restart gmond with systemd
    systemd:
      name: gmond
      state: restarted
      enabled: yes

  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

