# tasks to define a host object representing the current host and add to the related cfg file

- block:
  
  - name: Creat definitions for a host and related services
    template:
       src: check_ganglia_host_services.cfg.j2
       dest: /etc/nagios/conf.d/{{ cluster_item }}_host_{{ inventory_hostname }}.cfg

  when: outer_ansible_distribution == 'CentOS' or outer_ansible_distribution == 'RedHat'
