# tasks to install docker on hosts

- name: Install EPEL release
  become: yes
  yum:
    name: epel-release
    state: latest

- name: Install Docker by yum
  become: yes
  yum:
    name: docker
    state: present

- name: Enable and start the Docker service
  become: yes
  systemd:
    state: started
    enabled: yes
    name: docker